// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkv0Vtog0uD38LYRQO1nmI0hBbb_vXweU',
    appId: '1:338431945525:web:41fc11929c8859087ffa7c',
    messagingSenderId: '338431945525',
    projectId: 'rdtask-e7b00',
    authDomain: 'rdtask-e7b00.firebaseapp.com',
    storageBucket: 'rdtask-e7b00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK0fmYU2-H8DGxEFl1Kc5uZTsJNtq0GX4',
    appId: '1:338431945525:android:d543eede823796fe7ffa7c',
    messagingSenderId: '338431945525',
    projectId: 'rdtask-e7b00',
    storageBucket: 'rdtask-e7b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BKG-_uD6uXJmgkXbfZyixyIwMSgAnio',
    appId: '1:338431945525:ios:e554d0311e3b33e87ffa7c',
    messagingSenderId: '338431945525',
    projectId: 'rdtask-e7b00',
    storageBucket: 'rdtask-e7b00.appspot.com',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BKG-_uD6uXJmgkXbfZyixyIwMSgAnio',
    appId: '1:338431945525:ios:e554d0311e3b33e87ffa7c',
    messagingSenderId: '338431945525',
    projectId: 'rdtask-e7b00',
    storageBucket: 'rdtask-e7b00.appspot.com',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkv0Vtog0uD38LYRQO1nmI0hBbb_vXweU',
    appId: '1:338431945525:web:0269ade860ef87bd7ffa7c',
    messagingSenderId: '338431945525',
    projectId: 'rdtask-e7b00',
    authDomain: 'rdtask-e7b00.firebaseapp.com',
    storageBucket: 'rdtask-e7b00.appspot.com',
  );
}
